# Generated by Django 2.2.4 on 2019-08-24 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('cost', models.IntegerField()),
                ('pack_start_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField(max_length=39)),
                ('pimage', models.FileField(upload_to='photographer')),
            ],
        ),
        migrations.CreateModel(
            name='post_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=20)),
                ('country', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=20)),
                ('pimage', models.FileField(upload_to='photographer')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neptourapp.Photographer')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neptourapp.Photo')),
                ('photographer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neptourapp.Photographer')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neptourapp.Photographer'),
        ),
    ]
