# Generated by Django 2.2.4 on 2019-08-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neptourapp', '0003_auto_20190824_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(default=1, upload_to='post'),
            preserve_default=False,
        ),
    ]
