# Generated by Django 2.2.4 on 2019-08-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neptourapp', '0004_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='place',
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
