# Generated by Django 2.2.4 on 2019-08-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neptourapp', '0012_photographer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='username',
        ),
    ]
