# Generated by Django 2.2.4 on 2019-08-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neptourapp', '0014_photographer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
