# Generated by Django 2.2.4 on 2019-08-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neptourapp', '0015_auto_20190824_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
