# Generated by Django 2.2.4 on 2019-08-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neptourapp', '0017_auto_20190825_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photographer_name',
        ),
        migrations.AddField(
            model_name='post',
            name='photographer',
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
