# Generated by Django 2.2.4 on 2019-08-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neptourapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
