# Generated by Django 2.2.4 on 2019-08-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neptourapp', '0006_auto_20190824_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='pimage',
            field=models.FileField(blank=True, upload_to='photographer'),
        ),
    ]
