# Generated by Django 2.2.4 on 2019-08-24 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neptourapp', '0009_auto_20190824_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='username',
        ),
        migrations.RemoveField(
            model_name='tourist',
            name='username',
        ),
    ]
