# Generated by Django 2.2.4 on 2019-08-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neptourapp', '0010_auto_20190824_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='choice',
            field=models.CharField(choices=[('Tourist', 'Tourist'), ('Photographer', 'Photographer')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourist',
            name='choice',
            field=models.CharField(choices=[('Tourist', 'Tourist'), ('Photographer', 'Photographer')], max_length=100, null=True),
        ),
    ]
