# Generated by Django 2.2.4 on 2019-08-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neptourapp', '0016_auto_20190824_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='place',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
